# Generated by Django 3.2.8 on 2021-10-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('authentication', '0002_employee_token_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization'),
        ),
    ]
