# Generated by Django 3.2.8 on 2021-11-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
